version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db